---
- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present

- name: Verify Java version
  command: java -version
  register: java_version
  changed_when: false
  failed_when: "java_version.stderr | regex_search('openjdk version \"17') == None"

- name: Increase virtual memory limit
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes

- name: Add Elastic GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Set Elasticsearch directory permissions
  file:
    path: /etc/elasticsearch
    owner: elasticsearch
    group: elasticsearch
    recurse: yes

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Install Kibana
  apt:
    name: kibana
    state: present

- name: Install Filebeat
  apt:
    name: filebeat
    state: present

- name: Start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - filebeat
 
- name: Increase virtual memory limit (vm.max_map_count)
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes

- name: Ensure Elasticsearch directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  loop:
    - /etc/elasticsearch
    - /var/lib/elasticsearch
    - /var/log/elasticsearch

- name: Allow Elasticsearch port in firewall
  ufw:
    rule: allow
    port: 9200